FROM python:3.10-slim-buster

WORKDIR /app

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

COPY src/bot /app
COPY src/celery /app
COPY src/utils /app

RUN ls -la /app

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction --no-ansi

CMD ["python", "/bot/main.py"]