FROM python:3.10-slim-buster

WORKDIR /usr/app

ENV PYTHONUNBUFFERED=1

COPY src/celery /usr/app/src/celery
COPY src/utils /usr/app/src/utils
COPY pyproject.toml /usr/app

ENV PYTHONPATH "${PYTHONPATH}:/usr/app/src"

RUN pip install poetry
RUN python -m poetry config virtualenvs.create false
RUN python -m poetry install --no-interaction --no-ansi --no-root

CMD ["python", "-m", "celery", "-A", "celery/tasks", "worker", "-l", "info"]