version: "3.9"


services:
  redis:
    image: redis:7.0-alpine3.16
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - /data/redis:/data
  rabbit:
    image: rabbitmq:3.10-management-alpine
    restart: always
    hostname: alpha
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq/