FROM python:3.10-slim-buster

WORKDIR /usr/app

ENV PYTHONUNBUFFERED=1

COPY src /usr/app/src
COPY pyproject.toml /usr/app

ENV PYTHONPATH "${PYTHONPATH}:/usr/app/src"

RUN pip install poetry
RUN python -m poetry config virtualenvs.create false
RUN python -m poetry install --no-interaction --no-ansi --no-root

CMD ["python", "/src/bot/main.py"]