FROM python:3.10-slim-buster

WORKDIR /src

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

COPY src/bot /src
COPY src/celery /src
COPY src/utils /src
COPY pyproject.toml /src

RUN ls -la /src

RUN pip install poetry
RUN python -m poetry config virtualenvs.create false
RUN python -m poetry install --no-interaction --no-ansi --no-root

RUN ls -la /src

CMD ["python", "/bot/main.py"]