FROM python:3.10-slim-buster

WORKDIR /app

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

COPY src/bot /src
COPY src/celery /src
COPY src/utils /src

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

RUN ls -la /app

CMD ["python", "-m", "celery", "-A", "celery/tasks", "worker", "-l", "info"]